In [1]:
l=[23245,27,546,215,-1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
import numpy as np

In [5]:
a=np.array(l)

In [6]:
a

array([23245,    27,   546,   215, -1234])

In [9]:
b=np.array([12, 63.3, True, 'abc'])

In [10]:
print(b)

['12' '63.3' 'True' 'abc']


In [12]:
l.pop()

-1234

In [14]:
a.mean()

4559.8

In [15]:
a

array([23245,    27,   546,   215, -1234])

In [16]:
a[2:]

array([  546,   215, -1234])

In [18]:
a[::2]

array([23245,   546, -1234])

In [20]:
a[2:4]

array([546, 215])

In [22]:
b=a[2:4]

In [23]:
b

array([546, 215])

In [24]:
b[:]
#this is view of array a, not it's own array

array([546, 215])

In [27]:
b[:]=6

In [28]:
b

array([6, 6])

In [29]:
a

array([23245,    27,     6,     6, -1234])

In [ ]:
# answer is to make a copy 